import { StyleSheet } from 'react-native';
import { COLORS, FONTS } from './common';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 50,
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  menuBtn: {
    padding: 8,
    width: 40,
    justifyContent: 'center',
    gap: 5,
  },
  menuLine: {
    width: 22,
    height: 2,
    backgroundColor: COLORS.white,
    borderRadius: 1,
  },
  headerTitle: {
    fontFamily: FONTS.gowun,
    fontSize: 22,
    color: COLORS.white,
    marginLeft: 12,
  },
  filterScrollView: {
    height: 40,
    flexGrow: 0,
  },
  filterRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    alignItems: 'center',
    gap: 8,
    height: 40,
  },
  filterChip: {
    height: 28,
    paddingHorizontal: 14,
    borderRadius: 14,
    borderWidth: 0.5,
    borderColor: COLORS.whiteAlpha50,
    backgroundColor: 'rgba(255,255,255,0)',
    opacity: 0.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterChipActive: {
    borderColor: COLORS.white,
    opacity: 1,
  },
  filterChipText: {
    fontFamily: FONTS.gowun,
    fontSize: 13,
    color: COLORS.white,
  },
  fortuneScroll: {
    flex: 1,
  },
  listContent: {
    paddingHorizontal: 16,
    paddingBottom: 40,
    paddingTop: 4,
  },
  section: {
    marginBottom: 8,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 20,
    marginBottom: 10,
  },
  sectionAccent: {
    width: 3,
    height: 18,
    borderRadius: 2,
    backgroundColor: COLORS.purple,
  },
  sectionTitle: {
    fontFamily: FONTS.gowunBold,
    fontSize: 16,
    color: COLORS.white,
  },
  sectionItems: {
    gap: 8,
  },
  rankingList: {
    borderWidth: 1,
    borderColor: 'rgba(181,61,255,0.3)',
    borderRadius: 10,
    overflow: 'hidden',
  },
  rankingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
    gap: 12,
    backgroundColor: 'rgba(255,255,255,0.02)',
  },
  rankNumber: {
    fontFamily: FONTS.gowunBold,
    fontSize: 16,
    width: 22,
    textAlign: 'center',
  },
  rankName: {
    fontFamily: FONTS.gowun,
    fontSize: 14,
    color: COLORS.white,
    flex: 1,
  },
  rankBadge: {
    paddingHorizontal: 9,
    paddingVertical: 3,
    borderRadius: 10,
    backgroundColor: 'rgba(181,61,255,0.12)',
    borderWidth: 0.5,
    borderColor: 'rgba(181,61,255,0.5)',
  },
  rankBadgeText: {
    fontFamily: FONTS.gowun,
    fontSize: 11,
    color: 'rgba(181,61,255,0.9)',
  },
  fortuneCard: {
    borderWidth: 1,
    borderColor: 'rgba(255,250,250,1)',
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: 'rgba(255,255,255,0)',
  },
  fortuneCardTitle: {
    fontFamily: FONTS.gowun,
    fontSize: 20,
    color: COLORS.white,
    marginBottom: 4,
  },
  fortuneDuration: {
    fontFamily: FONTS.gowun,
    fontSize: 12,
    color: COLORS.whiteAlpha70,
    marginBottom: 6,
  },
  fortuneDescription: {
    fontFamily: FONTS.gowun,
    fontSize: 12,
    lineHeight: 18,
  },
  leftDots: {
    position: 'absolute',
    left: 8,
    gap: 0,
  },
  dot: {
    width: 9,
    height: 9,
    borderRadius: 4.5,
    backgroundColor: COLORS.white,
    marginVertical: 120,
  },
  infoBox: {
    marginHorizontal: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,1)',
    borderRadius: 0,
    overflow: 'hidden',
  },
  infoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    gap: 8,
  },
  infoHeaderGradient: {
    borderRadius: 30,
    paddingHorizontal: 12,
    paddingVertical: 3,
  },
  infoHeaderText: {
    fontFamily: FONTS.gowunBold,
    fontSize: 15,
    color: 'rgba(10,10,173,0.75)',
  },
  infoStar: {
    color: COLORS.whiteAlpha70,
    fontSize: 12,
  },
  infoBody: {
    paddingHorizontal: 16,
    paddingBottom: 12,
    fontFamily: FONTS.gowunBold,
    fontSize: 15,
    color: COLORS.white,
  },
  sidebarOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 100,
  },
  sidebarBg: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  sidebarPanel: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    width: 280,
    zIndex: 101,
  },
  sidebar: {
    flex: 1,
    paddingTop: 40,
    paddingHorizontal: 24,
  },
  sidebarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 32,
  },
  sidebarTitle: {
    fontFamily: FONTS.gowun,
    fontSize: 18,
    color: COLORS.white,
    opacity: 0.8,
  },
  closeBtn: {
    padding: 4,
    opacity: 0.8,
  },
  closeBtnText: {
    color: COLORS.white,
    fontSize: 20,
  },
  sidebarProfile: {
    alignItems: 'center',
    marginBottom: 20,
  },
  profileCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: 'rgba(181,61,255,0.15)',
    borderWidth: 1.5,
    borderColor: 'rgba(181,61,255,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    overflow: 'hidden',
  },
  profileImg: {
    width: 72,
    height: 72,
    borderRadius: 36,
  },
  profileDefaultIcon: {
    fontSize: 32,
    color: COLORS.whiteAlpha70,
  },
  sidebarUserName: {
    fontFamily: FONTS.gowunBold,
    fontSize: 16,
    color: COLORS.white,
  },
  sidebarDivider: {
    height: 1,
    backgroundColor: 'rgba(255,246,246,0.5)',
    marginBottom: 20,
  },
  sidebarItem: {
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,246,246,0.5)',
  },
  sidebarItemText: {
    fontFamily: FONTS.gowun,
    fontSize: 18,
    color: COLORS.white,
  },
});
