import { StyleSheet } from 'react-native';
import { COLORS, FONTS } from './common';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  mainContent: {
    flex: 1,
    justifyContent: 'space-between',
  },
  headerArea: {
    paddingTop: 72,
    paddingHorizontal: 24,
    paddingBottom: 12,
  },
  titleKor: {
    fontFamily: FONTS.gowun,
    fontSize: 62,
    color: COLORS.white,
    lineHeight: 76,
    textShadowColor: 'rgba(181,61,255,0.4)',
    textShadowRadius: 12,
  },
  titleEng: {
    fontFamily: FONTS.fuggles,
    fontSize: 30,
    color: COLORS.whiteAlpha70,
    position: 'absolute',
    top: 52,
    right: 16,
  },
  decorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  decorLine: {
    flex: 1,
    height: 1,
    backgroundColor: COLORS.whiteAlpha40,
  },
  decorText: {
    fontFamily: FONTS.fuggles,
    fontSize: 18,
    color: COLORS.whiteAlpha40,
    marginHorizontal: 12,
  },
  cardSection: {
    marginHorizontal: 8,
    marginTop: 8,
    borderRadius: 5,
    overflow: 'hidden',
  },
  cardSectionBg: {
    padding: 16,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(177,75,255,0.43)',
    borderRadius: 5,
  },
  sectionTitle1: {
    fontFamily: FONTS.gowun,
    fontSize: 30,
    lineHeight: 38,
  },
  sectionTitle2: {
    fontFamily: FONTS.gowun,
    fontSize: 30,
    marginTop: 2,
  },
  previewCardsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 16,
    marginTop: 16,
    marginBottom: 4,
  },
  previewCardWrap: {
    alignItems: 'center',
    gap: 8,
  },
  previewCardLabel: {
    fontFamily: FONTS.gowun,
    fontSize: 14,
    color: COLORS.whiteAlpha70,
  },
  hashtagRow: {
    marginTop: 14,
    paddingHorizontal: 4,
  },
  hashtagText: {
    fontFamily: FONTS.gowun,
    fontSize: 14,
    color: COLORS.highlightBlue,
    lineHeight: 22,
  },
  bottomGroup: {
    paddingHorizontal: 8,
    paddingBottom: 20,
    gap: 12,
  },
  ctaButton: {
    borderRadius: 10,
    overflow: 'hidden',
  },
  ctaButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    paddingHorizontal: 20,
    gap: 10,
  },
  ctaButtonText: {
    fontFamily: FONTS.gowun,
    fontSize: 20,
    color: COLORS.white,
    letterSpacing: 0.5,
  },
  ctaArrow: {
    color: COLORS.white,
    fontSize: 20,
  },
  loginNudge: {
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.whiteAlpha40,
    backgroundColor: 'rgba(181,61,255,0.1)',
    alignItems: 'center',
  },
  loginNudgeText: {
    fontFamily: FONTS.gowun,
    fontSize: 13,
    color: COLORS.whiteAlpha70,
    textAlign: 'center',
    lineHeight: 20,
  },
  loginNudgeBtn: {
    marginTop: 8,
    paddingHorizontal: 20,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.purple,
  },
  loginNudgeBtnText: {
    fontFamily: FONTS.gowun,
    fontSize: 13,
    color: COLORS.purple,
  },
  leftDots: {
    position: 'absolute',
    left: 8,
    top: 160,
    gap: 110,
  },
  dot: {
    width: 9,
    height: 9,
    borderRadius: 4.5,
    backgroundColor: COLORS.white,
    opacity: 0.7,
  },
  hamburgerBtn: {
    position: 'absolute',
    top: 52,
    right: 16,
    zIndex: 100,
    padding: 8,
    gap: 5,
  },
  hamburgerLine: {
    width: 24,
    height: 2,
    borderRadius: 1,
    backgroundColor: COLORS.white,
    opacity: 0.85,
  },
  drawerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 200,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  drawer: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: 200,
    backgroundColor: '#1a0035',
    borderLeftWidth: 1,
    borderLeftColor: 'rgba(177,75,255,0.35)',
    paddingTop: 72,
    paddingHorizontal: 20,
  },
  drawerTitle: {
    fontFamily: FONTS.gowun,
    fontSize: 18,
    color: COLORS.white,
    marginBottom: 12,
  },
  drawerDivider: {
    height: 1,
    backgroundColor: 'rgba(177,75,255,0.3)',
    marginBottom: 20,
  },
  drawerItem: {
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.07)',
  },
  drawerItemText: {
    fontFamily: FONTS.gowun,
    fontSize: 16,
    color: 'rgba(255,100,100,0.9)',
  },
});
