import { StyleSheet } from 'react-native';
import { COLORS, FONTS } from './common';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  header: {
    paddingTop: 54,
    paddingHorizontal: 20,
    alignItems: 'center',
    marginBottom: 12,
  },
  headerTitle: {
    fontFamily: FONTS.gowun,
    fontSize: 20,
    color: COLORS.whiteAlpha70,
    textAlign: 'center',
    letterSpacing: 2,
  },
  fortuneTypeLabel: {
    fontFamily: FONTS.gowun,
    fontSize: 13,
    color: COLORS.whiteAlpha60,
    marginTop: 4,
    marginBottom: 12,
  },
  mainCard: {
    marginHorizontal: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,248,248,0.5)',
    borderRadius: 5,
    padding: 20,
    alignItems: 'center',
  },
  tarotImageWrap: {
    alignItems: 'center',
    marginBottom: 14,
  },
  cardName: {
    fontFamily: FONTS.gowun,
    fontSize: 17,
    color: COLORS.white,
    letterSpacing: 1.5,
    textAlign: 'center',
    marginBottom: 10,
  },
  keywordsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 6,
    marginBottom: 16,
  },
  keywordChip: {
    borderWidth: 1,
    borderColor: 'rgba(181,61,255,0.55)',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 3,
    backgroundColor: 'rgba(181,61,255,0.08)',
  },
  keywordText: {
    fontFamily: FONTS.gowun,
    fontSize: 12,
    color: COLORS.whiteAlpha80,
    letterSpacing: 0.3,
  },
  readingBox: {
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(255,248,248,0.4)',
    borderRadius: 5,
    padding: 16,
    marginTop: 4,
  },
  readingCardDesc: {
    fontFamily: FONTS.gowun,
    fontSize: 14,
    color: COLORS.whiteAlpha80,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 12,
  },
  readingDivider: {
    height: 0.6,
    backgroundColor: 'rgba(181,61,255,0.3)',
    marginBottom: 14,
  },
  readingAiLabel: {
    fontFamily: FONTS.gowun,
    fontSize: 12,
    color: 'rgba(181,61,255,0.8)',
    textAlign: 'center',
    letterSpacing: 1.5,
    marginBottom: 10,
  },
  readingPlaceholder: {
    fontFamily: FONTS.gowun,
    fontSize: 13,
    color: COLORS.whiteAlpha50,
    textAlign: 'center',
    lineHeight: 22,
  },
  readingText: {
    fontFamily: FONTS.gowun,
    fontSize: 16,
    color: COLORS.whiteAlpha80,
    lineHeight: 28,
  },
  actionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 18,
    marginTop: 20,
    gap: 12,
  },
  actionBtn: {
    flex: 1,
    paddingVertical: 14,
    alignItems: 'center',
    borderRadius: 4,
  },
  actionBtnText: {
    fontFamily: FONTS.gowun,
    fontSize: 15,
    color: COLORS.white,
    textAlign: 'center',
  },
  homeBtn: {
    marginHorizontal: 18,
    marginTop: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  homeBtnArrow: {
    color: COLORS.whiteAlpha60,
    fontSize: 16,
  },
  homeBtnText: {
    fontFamily: FONTS.gowun,
    fontSize: 16,
    color: COLORS.white,
  },
});
